#!/usr/bin/env bash
set -e

SRC=$(find . -type d -name "src" -not -path "./.venv/*" | head -1)

if [[ -z "$SRC" ]]; then
    echo "Could not find src folder"
    exit 1
fi


if [[ -f ".venv/Scripts/python" ]]; then
    PYTHON=".venv/Scripts/python"      # Windows
else
    PYTHON=".venv/bin/python"          # Linux/Mac
fi

"$PYTHON" "$SRC/main.py"